#!/bin/sh
GOOS=darwin GOARCH=amd64 go build -o bin/redisee_darwin_amd64 .
GOOS=darwin GOARCH=arm64 go build -o bin/redisee_darwin_arm64 .

GOOS=linux GOARCH=amd64 go build -o bin/redisee_linux_amd64 .
GOOS=linux GOARCH=386 go build -o bin/redisee_linux_386 .
GOOS=linux GOARCH=arm go build -o bin/redisee_linux_arm .
GOOS=linux GOARCH=arm64 go build -o bin/redisee_linux_arm64 .

GOOS=windows GOARCH=amd64 go build -o bin/redisee_windows_amd64.exe .
GOOS=windows GOARCH=386 go build -o bin/redisee_windows_386.exe .